### PR TITLE
Use mattermost-server/v6

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR updates the dependency on `github.com/mattermost/mattermost-server` from `v5` to `v6`. This ensures the v6 breaking changes propagate quickly to developers using this plugin.

Please note that the plugin still works against v5 servers.

#### Ticket Link
None

### CODE REVIEW

**Comment by mickmister** [comment]
We need to bump the `min_server_version` to `5.37`, similar to https://github.com/mattermost/mattermost-marketplace/pull/233

**Comment by mickmister** [comment]
Our conclusive plan after the incompatibility issue was that we would always import from a specific Mattermost version (not commit, though I see in this PR we are importing using a version), and set the `min_server_version` to that version. We haven't been following it, but that is what we arrived at to make sure we don't run into similar incombatibility issues in the future.

**Comment by hanzei** [comment]
@mickmister Thanks for spotting that. Fixed :+1:

**Comment by hanzei** [comment]
@sibasankarnayak Gentle reminder to review the PR

**Review by sibasankarnayak — APPROVED** [review]
LGTM!

**Comment by DHaussermann** [comment]
@hanzei, @dipak-demansol and I have completed the round of release testing for `v1.1.1` Any thoughts on if this required for `1.1.1` as the milestone is set here?

**Comment by hanzei** [comment]
@DHaussermann No, this PR isn't required for `v1.1.1`, but given that its low risk, I'm incident to merge it anyway.

**Comment by hanzei** [comment]
@mickmister Gentle reminder to review the PR

**Review by mickmister — APPROVED** [review]
LGTM :+1: just one request to revert the changes in `webapp/package-lock.json`. We should update the lock file, but in a separate PR.

**Comment by hanzei** [comment]
I'm going to skip QA review as this PR contains mostly tooling changes.

**Pull request merged**
