### PR TITLE
[issue-77] Auto Complete Don't have the bitbucket icon #77

### LINKED ISSUE #77: Auto Complete Don't have the bitbucket icon
bitbuket-autocomplete-icon-missing

### PR DESCRIPTION
**Pull request by sibasankarnayak**
added icon for bitbucket autocommand

ticket here
Fixes #77

### CODE REVIEW

**Comment by hanzei** [comment]
Could you please share a screenshots with a dark and a bright theme?

**Comment by sibasankarnayak** [comment]
@hanzei 

> Could you please share a screenshots with a dark and a bright theme?

@hanzei sure 
image
image

**Review by matthewbirtch — APPROVED** [review]
Looks good based on the screenshots

**Review by mickmister — APPROVED** [review]

**Review by dipak-demansol — APPROVED** [review]
LGTM

**Review by jfrerich — APPROVED** [review]

**Pull request merged**
