### PR TITLE
[mm 52] Resolve OAuth bug with KVStore

### LINKED ISSUE #52: Resolve OAuth bug with KVStore
Details will be shared in the weekly MM-Demansol meeting. Update: the've been shared with Siba on the call.

### PR DESCRIPTION
**Pull request by sibasankarnayak**
fixed the logic of complete the oauth complete redirect

Fixes #52

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Blocking until https://github.com/mattermost/mattermost-plugin-github/pull/511 is approved

**Review by hanzei — APPROVED** [review]

**Review by catalintomai — APPROVED** [review]

**Comment by hanzei** [comment]
@dipak-demansol This is the same solution as https://github.com/mattermost/mattermost-plugin-github/pull/511. Hence, I'm incident to merge this PR with QA review once you approved https://github.com/mattermost/mattermost-plugin-github/pull/511. Does that sound good to you?

**Comment by dipak-demansol** [comment]
> @dipak-demansol This is the same solution as [mattermost/mattermost-plugin-github#511](https://github.com/mattermost/mattermost-plugin-github/pull/511). Hence, I'm incident to merge this PR with QA review once you approved [mattermost/mattermost-plugin-github#511](https://github.com/mattermost/mattermost-plugin-github/pull/511). Does that sound good to you?

yes sir.

**Comment by dipak-demansol** [comment]
> @dipak-demansol This is the same solution as [mattermost/mattermost-plugin-github#511](https://github.com/mattermost/mattermost-plugin-github/pull/511). Hence, I'm incident to merge this PR with QA review once you approved [mattermost/mattermost-plugin-github#511](https://github.com/mattermost/mattermost-plugin-github/pull/511). Does that sound good to you?

@hanzei After GitHub PR merge, you can also merge this PR, will add the test cases for this & GitHub PR in the zypher and will do the the testing for both at the time of release or Regression.

**Review by dipak-demansol — APPROVED** [review]
**As Per #511 This is LGTM,** will do the testing of this at the time of release or Regression.

**Pull request merged**
